
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  batch:
    job:
      enabled: false  # 자동 실행 활성화
    jdbc:
      initialize-schema: never  # 스키마 자동 초기화, 이미 생겨서 always -> never 로변경
  sql:
    init:
      mode: never # 이미 생겨서 always -> never 로변경
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG